services:
  - type: web
    name: live-ai
    env: python
    buildCommand: |
      apt-get update && apt-get install -y portaudio19-dev
      pip install --user -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11